{% set name = "oxasl" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oxasl-{{ version }}.tar.gz
  sha256: 499e17ac9133811040e001dec122dd0acb9f2dbe541630c535c31c1f10a1dc74

build:
  number: 0
  noarch: python
  entry_points:
    - oxasl_preproc=oxasl.preproc:main
    - oxasl_basil=oxasl.basil:main
    - oxasl_calib=oxasl.calib:main
    - oxasl_mask=oxasl.mask:main
    - oxasl_reg=oxasl.reg:main
    - oxasl=oxasl.oxford_asl:main
    - oxasl_gui=oxasl.gui:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - sphinx
  run:
    - fslpy >=1.13
    - nibabel
    - numpy
    - pandas
    - pyaml
    - pyfab
    - python >=3.6
    - scikit-image
    - six

test:
  imports:
    - oxasl
  commands:
    - oxasl_preproc --help
    - oxasl_basil --help
    - oxasl_calib --help
    - oxasl_mask --help
    - oxasl_reg --help
    - oxasl --help
  requires:
    - pip

about:
  home: https://oxasl.readthedocs.io/
  summary: Python library for manipulating and modelling ASL data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
